### ISSUE TITLE
Update jsdom

### ISSUE THREAD

**Issue by marcandre** [jmeas/simple-jsdom#10]
FYI, we had an issue that turned out to be because `jsdom` was (way) too old. https://github.com/guillaumepotier/Parsley.js/issues/1095

**Comment by jamesplease** [comment]
This lib supports the latest JSDom as of [v2](https://github.com/jmeas/simple-jsdom/releases/tag/2.0.0) released on March 21. Seems like you needed to update `simple-jsdom` on your end.

**Comment by jamesplease** [comment]
p.s. I use this on a bunch of projects so I plan to keep it up-to-date! :v:
